/* swaves.js — the three shooter stages as wave timelines over Izu. Each stage:
   backdrop art, music, a timeline of spawns (t = seconds), then a boss. Facts
   from data/facts.js show on the stage-clear card (same as the adventure). */

// helper: relative Y (0..1 of screen height)
const RY = (k) => Engine.H * k;

const SSTAGES = [
  {
    name: '城ヶ崎かいがん', sub: 'なみの うえを ゆけ！', bg: 'sh_bg_coast', night: false,
    music: 'sky', boss: 'octo', factId: 'jogasaki', clearSprite: 'l_lighthouse2',
    bossAt: 58,
    waves: [
      { t: 2.0, f: (S) => S.spawnRow('gull', [0.3, 0.5, 0.7]) },
      { t: 5.5, f: (S) => S.spawnV('fish', 0.5, 5) },
      { t: 9.0, f: (S) => S.spawnRow('gull', [0.25, 0.75], { amp: 90 }) },
      { t: 12.0, f: (S) => S.spawn('jelly', 0.35) },
      { t: 13.0, f: (S) => S.spawn('jelly', 0.65) },
      { t: 16.0, f: (S) => S.spawnV('fish', 0.3, 4) },
      { t: 17.5, f: (S) => S.spawnV('fish', 0.7, 4) },
      { t: 21.0, f: (S) => S.spawnRow('mine', [0.25, 0.5, 0.75]) },
      { t: 24.0, f: (S) => S.spawn('octo', 0.5) },
      { t: 26.0, f: (S) => S.spawnRow('gull', [0.2, 0.4, 0.6, 0.8], { spd: 60 }) },
      { t: 30.0, f: (S) => S.drop('power', 0.4) },
      { t: 33.0, f: (S) => { S.spawn('jelly', 0.25); S.spawn('jelly', 0.75); } },
      { t: 36.0, f: (S) => S.spawnV('fish', 0.5, 6) },
      { t: 39.0, f: (S) => S.spawnRow('mine', [0.35, 0.65]) },
      { t: 42.0, f: (S) => S.spawn('octo', 0.3) },
      { t: 43.5, f: (S) => S.spawn('octo', 0.7) },
      { t: 47.0, f: (S) => S.spawnRow('gull', [0.3, 0.5, 0.7], { amp: 110, frq: 3.2 }) },
      { t: 50.0, f: (S) => S.drop('bomb', 0.6) },
      { t: 52.0, f: (S) => S.spawnV('fish', 0.4, 5) },
      { t: 54.0, f: (S) => S.spawnV('fish', 0.6, 5) },
    ],
  },
  {
    name: '大室山 じょうくう', sub: 'くもを こえて', bg: 'sh_bg_sky', night: false,
    music: 'sky', boss: 'gull', factId: 'omuro', clearSprite: 'l_omuro_big',
    bossAt: 62,
    waves: [
      { t: 2.0, f: (S) => S.spawnRow('gull', [0.2, 0.5, 0.8], { spd: 60 }) },
      { t: 5.0, f: (S) => S.spawn('jelly', 0.5) },
      { t: 7.5, f: (S) => S.spawnV('fish', 0.35, 5) },
      { t: 9.0, f: (S) => S.spawnV('fish', 0.65, 5) },
      { t: 12.0, f: (S) => S.spawnRow('mine', [0.2, 0.45, 0.7]) },
      { t: 15.0, f: (S) => S.spawnRow('gull', [0.3, 0.6], { amp: 130, frq: 3.4, spd: 100 }) },
      { t: 18.5, f: (S) => S.spawn('octo', 0.4) },
      { t: 21.0, f: (S) => S.spawn('jelly', 0.2) },
      { t: 22.0, f: (S) => S.spawn('jelly', 0.8) },
      { t: 25.0, f: (S) => S.drop('power', 0.5) },
      { t: 27.0, f: (S) => S.spawnV('fish', 0.5, 7) },
      { t: 30.0, f: (S) => S.spawnRow('gull', [0.25, 0.5, 0.75], { spd: 120 }) },
      { t: 34.0, f: (S) => S.spawnRow('mine', [0.3, 0.55, 0.8]) },
      { t: 37.0, f: (S) => { S.spawn('octo', 0.25); S.spawn('octo', 0.75); } },
      { t: 41.0, f: (S) => S.spawnRow('gull', [0.2, 0.4, 0.6, 0.8], { amp: 80 }) },
      { t: 45.0, f: (S) => S.drop('heart', 0.5) },
      { t: 47.0, f: (S) => S.spawnV('fish', 0.3, 5) },
      { t: 48.5, f: (S) => S.spawnV('fish', 0.7, 5) },
      { t: 52.0, f: (S) => S.spawnRow('mine', [0.25, 0.5, 0.75]) },
      { t: 55.0, f: (S) => S.spawn('jelly', 0.4) },
      { t: 56.0, f: (S) => S.spawn('jelly', 0.6) },
      { t: 58.0, f: (S) => S.drop('bomb', 0.5) },
    ],
  },
  {
    name: 'よるの 伊東おんせん', sub: 'さいごの たたかい', bg: 'sh_bg_night', night: true,
    music: 'night', boss: 'urchin', factId: 'ito_onsen', clearSprite: 'ryokan',
    bossAt: 66,
    waves: [
      { t: 2.0, f: (S) => S.spawn('ghost', 0.4) },
      { t: 3.0, f: (S) => S.spawn('ghost', 0.6) },
      { t: 6.0, f: (S) => S.spawn('lantern', 0.3) },
      { t: 7.5, f: (S) => S.spawn('lantern', 0.7) },
      { t: 11.0, f: (S) => S.spawnV('fish', 0.5, 5) },
      { t: 14.0, f: (S) => S.spawnRow('gull', [0.3, 0.7], { spd: 80 }) },
      { t: 17.0, f: (S) => { S.spawn('ghost', 0.25); S.spawn('ghost', 0.75); } },
      { t: 20.0, f: (S) => S.spawnRow('mine', [0.3, 0.5, 0.7]) },
      { t: 23.5, f: (S) => S.spawn('octo', 0.5) },
      { t: 26.0, f: (S) => S.spawn('lantern', 0.2) },
      { t: 27.0, f: (S) => S.spawn('lantern', 0.8) },
      { t: 30.0, f: (S) => S.drop('power', 0.5) },
      { t: 32.0, f: (S) => S.spawnV('fish', 0.35, 6) },
      { t: 34.0, f: (S) => S.spawnV('fish', 0.65, 6) },
      { t: 37.5, f: (S) => { S.spawn('ghost', 0.3); S.spawn('ghost', 0.5); S.spawn('ghost', 0.7); } },
      { t: 41.0, f: (S) => S.spawnRow('mine', [0.2, 0.4, 0.6, 0.8]) },
      { t: 45.0, f: (S) => { S.spawn('octo', 0.3); S.spawn('octo', 0.7); } },
      { t: 49.0, f: (S) => S.drop('heart', 0.4) },
      { t: 51.0, f: (S) => S.spawnRow('gull', [0.25, 0.5, 0.75], { amp: 120, spd: 110 }) },
      { t: 55.0, f: (S) => { S.spawn('lantern', 0.35); S.spawn('lantern', 0.65); } },
      { t: 58.0, f: (S) => S.spawnV('fish', 0.5, 7) },
      { t: 61.0, f: (S) => S.drop('bomb', 0.5) },
      { t: 62.5, f: (S) => { S.spawn('ghost', 0.4); S.spawn('ghost', 0.6); } },
    ],
  },
];

window.SSTAGES = SSTAGES;
