/* swaves.js — nine shooter stages in a 3-world × 3-sub layout (1-1 … 3-3).
   Sub-stages 1 and 2 of each world end in a mid-boss; sub-stage 3 ends in the
   world boss. Verified Izu facts show on the world-clear card (x-3 only).
   bossAt = seconds until the (mid-)boss warning. */

// helper: relative Y (0..1 of screen height)
const RY = (k) => Engine.H * k;

const SSTAGES = [
  // ============================ WORLD 1: 城ヶ崎かいがん =====================
  {
    name: '1-1 城ヶ崎かいがん', sub: 'パトロール かいし！', bg: 'sh_bg_coast', night: false,
    music: 'sky', boss: 'mid_tobiuo', bossHpMul: 1, factId: 'jogasaki', clearSprite: 'l_lighthouse2',
    bossAt: 40,
    waves: [
      { t: 2.0, f: (S) => S.spawnRow('gull', [0.3, 0.5, 0.7]) },
      { t: 5.5, f: (S) => S.spawnV('fish', 0.5, 5) },
      { t: 9.0, f: (S) => S.spawnRow('gull', [0.25, 0.75], { amp: 90 }) },
      { t: 12.0, f: (S) => { S.spawn('jelly', 0.35); S.spawn('jelly', 0.65); } },
      { t: 15.5, f: (S) => { S.spawn('tobiuoLeap', 0); S.spawn('tobiuoLeap', 0); } },
      { t: 18.0, f: (S) => S.spawnV('fish', 0.35, 4) },
      { t: 20.0, f: (S) => S.spawnRow('mine', [0.3, 0.7]) },
      { t: 23.0, f: (S) => S.spawnRow('gullDive', [0.4, 0.6]) },
      { t: 26.0, f: (S) => S.drop('power', 0.45) },
      { t: 28.0, f: (S) => { S.spawn('tobiuoLeap', 0); S.spawnV('fish', 0.6, 4); } },
      { t: 31.0, f: (S) => S.spawn('octo', 0.5) },
      { t: 34.0, f: (S) => S.spawnRow('gull', [0.2, 0.5, 0.8], { spd: 60 }) },
      { t: 37.0, f: (S) => S.drop('bomb', 0.55) },
    ],
  },
  {
    name: '1-2 しおかぜ すいどう', sub: 'なみまの きらめき', bg: 'sh_bg_coast', night: false,
    music: 'sky', boss: 'mid_mine', bossHpMul: 1, factId: 'jogasaki', clearSprite: 'l_lighthouse2',
    bossAt: 44,
    waves: [
      { t: 2.0, f: (S) => S.spawnV('fish', 0.4, 5) },
      { t: 4.5, f: (S) => S.spawnRow('gullDive', [0.3, 0.7]) },
      { t: 8.0, f: (S) => S.spawnRow('mine', [0.25, 0.5, 0.75]) },
      { t: 11.0, f: (S) => S.spawn('octoBack', 0.45) },
      { t: 14.0, f: (S) => { S.spawn('tobiuoLeap', 0); S.spawn('tobiuoLeap', 0); S.spawn('tobiuoLeap', 0); } },
      { t: 17.5, f: (S) => S.spawnRow('gull', [0.3, 0.6], { amp: 120, frq: 3.2 }) },
      { t: 21.0, f: (S) => { S.spawn('jelly', 0.25); S.spawn('jelly', 0.75); } },
      { t: 24.0, f: (S) => S.drop('power', 0.5) },
      { t: 26.0, f: (S) => S.spawnRow('gullDive', [0.25, 0.5, 0.75]) },
      { t: 29.5, f: (S) => { S.spawn('octo', 0.3); S.spawn('octo', 0.7); } },
      { t: 33.0, f: (S) => S.spawnV('fish', 0.5, 6) },
      { t: 36.0, f: (S) => S.spawnRow('mine', [0.35, 0.65]) },
      { t: 39.0, f: (S) => S.drop('heart', 0.5) },
      { t: 41.0, f: (S) => { S.spawn('tobiuoLeap', 0); S.spawn('tobiuoLeap', 0); } },
    ],
  },
  {
    name: '1-3 とうだいの みさき', sub: 'ていとくが まちうける', bg: 'sh_bg_coast', night: false,
    music: 'sky', boss: 'octo', bossHpMul: 1, factId: 'jogasaki', clearSprite: 'l_lighthouse2',
    worldEnd: true, bossAt: 48,
    waves: [
      { t: 2.0, f: (S) => S.spawnRow('gull', [0.2, 0.4, 0.6, 0.8]) },
      { t: 5.5, f: (S) => { S.spawn('octoBack', 0.35); S.spawn('jelly', 0.7); } },
      { t: 9.0, f: (S) => S.spawnV('fish', 0.3, 5) },
      { t: 10.5, f: (S) => S.spawnV('fish', 0.7, 5) },
      { t: 14.0, f: (S) => S.spawnRow('mine', [0.2, 0.45, 0.7]) },
      { t: 17.0, f: (S) => S.spawnRow('gullDive', [0.3, 0.5, 0.7]) },
      { t: 20.5, f: (S) => { S.spawn('tobiuoLeap', 0); S.spawn('tobiuoLeap', 0); S.spawn('tobiuoLeap', 0); } },
      { t: 24.0, f: (S) => S.drop('power', 0.4) },
      { t: 26.0, f: (S) => { S.spawn('octo', 0.25); S.spawn('octo', 0.75); } },
      { t: 30.0, f: (S) => S.spawnRow('gull', [0.3, 0.5, 0.7], { amp: 110, spd: 80 }) },
      { t: 33.5, f: (S) => { S.spawnRow('mine', [0.3, 0.7]); S.spawn('jelly', 0.5); } },
      { t: 37.0, f: (S) => S.spawnRow('gullDive', [0.4, 0.6]) },
      { t: 40.0, f: (S) => S.drop('bomb', 0.5) },
      { t: 42.0, f: (S) => S.spawnV('fish', 0.5, 7) },
      { t: 45.0, f: (S) => { S.spawn('tobiuoLeap', 0); S.spawn('tobiuoLeap', 0); } },
    ],
  },

  // ============================ WORLD 2: 大室山じょうくう ===================
  {
    name: '2-1 くもの かいどう', sub: 'そらの たかみへ', bg: 'sh_bg_sky', night: false,
    music: 'sky', boss: 'mid_tobiuo', bossHpMul: 1.25, factId: 'omuro', clearSprite: 'l_omuro_big',
    bossAt: 42,
    waves: [
      { t: 2.0, f: (S) => S.spawnRow('gull', [0.25, 0.5, 0.75], { spd: 60 }) },
      { t: 5.0, f: (S) => S.spawnRow('gullDive', [0.35, 0.65]) },
      { t: 8.5, f: (S) => S.spawnV('fish', 0.5, 6) },
      { t: 11.5, f: (S) => S.spawnRow('mine', [0.2, 0.5, 0.8]) },
      { t: 14.5, f: (S) => S.spawn('octoBack', 0.5) },
      { t: 18.0, f: (S) => S.spawnRow('gull', [0.3, 0.6], { amp: 140, frq: 3.4, spd: 110 }) },
      { t: 21.0, f: (S) => { S.spawn('jelly', 0.3); S.spawn('jelly', 0.7); } },
      { t: 24.0, f: (S) => S.drop('power', 0.5) },
      { t: 26.0, f: (S) => S.spawnRow('gullDive', [0.25, 0.5, 0.75]) },
      { t: 29.5, f: (S) => S.spawnV('fish', 0.35, 5) },
      { t: 31.0, f: (S) => S.spawnV('fish', 0.65, 5) },
      { t: 34.5, f: (S) => { S.spawn('octo', 0.4); S.spawnRow('mine', [0.7]) ; } },
      { t: 38.0, f: (S) => S.drop('bomb', 0.5) },
    ],
  },
  {
    name: '2-2 かざんの かぜ', sub: 'じょうしょう きりゅう', bg: 'sh_bg_sky', night: false,
    music: 'sky', boss: 'mid_mine', bossHpMul: 1.25, factId: 'omuro', clearSprite: 'l_omuro_big',
    bossAt: 45,
    waves: [
      { t: 2.0, f: (S) => S.spawnRow('mine', [0.3, 0.5, 0.7]) },
      { t: 5.0, f: (S) => S.spawnRow('gullDive', [0.3, 0.7]) },
      { t: 8.0, f: (S) => { S.spawn('octoBack', 0.3); S.spawn('octoBack', 0.7); } },
      { t: 12.0, f: (S) => S.spawnV('fish', 0.5, 7) },
      { t: 15.0, f: (S) => S.spawnRow('gull', [0.2, 0.4, 0.6, 0.8], { spd: 90 }) },
      { t: 18.5, f: (S) => { S.spawn('jelly', 0.2); S.spawn('jelly', 0.5); S.spawn('jelly', 0.8); } },
      { t: 22.0, f: (S) => S.drop('power', 0.45) },
      { t: 24.0, f: (S) => S.spawnRow('gullDive', [0.2, 0.45, 0.7]) },
      { t: 27.5, f: (S) => S.spawnRow('mine', [0.25, 0.5, 0.75]) },
      { t: 31.0, f: (S) => { S.spawn('octo', 0.35); S.spawn('octo', 0.65); } },
      { t: 34.5, f: (S) => S.spawnV('fish', 0.3, 5) },
      { t: 36.0, f: (S) => S.spawnV('fish', 0.7, 5) },
      { t: 39.5, f: (S) => S.drop('heart', 0.5) },
      { t: 41.5, f: (S) => S.spawnRow('gull', [0.3, 0.5, 0.7], { amp: 120 }) },
    ],
  },
  {
    name: '2-3 さんちょうの あらし', sub: 'たいちょうとの けっせん', bg: 'sh_bg_sky', night: false,
    music: 'sky', boss: 'gull', bossHpMul: 1, factId: 'omuro', clearSprite: 'l_omuro_big',
    worldEnd: true, bossAt: 50,
    waves: [
      { t: 2.0, f: (S) => S.spawnRow('gullDive', [0.3, 0.5, 0.7]) },
      { t: 5.5, f: (S) => S.spawnRow('gull', [0.2, 0.8], { amp: 150, frq: 3.6, spd: 120 }) },
      { t: 9.0, f: (S) => { S.spawn('octoBack', 0.45); S.spawnV('fish', 0.7, 4); } },
      { t: 12.5, f: (S) => S.spawnRow('mine', [0.2, 0.4, 0.6, 0.8]) },
      { t: 16.0, f: (S) => { S.spawn('jelly', 0.25); S.spawn('jelly', 0.75); S.spawn('tobiuoLeap', 0); } },
      { t: 19.5, f: (S) => S.spawnRow('gullDive', [0.25, 0.5, 0.75]) },
      { t: 23.0, f: (S) => S.drop('power', 0.4) },
      { t: 25.0, f: (S) => { S.spawn('octo', 0.3); S.spawn('octo', 0.7); } },
      { t: 28.5, f: (S) => S.spawnV('fish', 0.5, 8) },
      { t: 32.0, f: (S) => S.spawnRow('gull', [0.25, 0.5, 0.75], { spd: 100 }) },
      { t: 35.5, f: (S) => { S.spawnRow('mine', [0.3, 0.7]); S.spawn('octoBack', 0.5); } },
      { t: 39.0, f: (S) => S.spawnRow('gullDive', [0.35, 0.65]) },
      { t: 42.0, f: (S) => S.drop('bomb', 0.5) },
      { t: 44.0, f: (S) => { S.spawn('tobiuoLeap', 0); S.spawn('tobiuoLeap', 0); } },
      { t: 46.5, f: (S) => S.spawnV('fish', 0.5, 6) },
    ],
  },

  // ============================ WORLD 3: よるの伊東おんせん =================
  {
    name: '3-1 ゆけむり よこちょう', sub: 'よるの まちに ひかりが', bg: 'sh_bg_night', night: true,
    music: 'night', boss: 'mid_lantern', bossHpMul: 1, factId: 'ito_onsen', clearSprite: 'ryokan',
    bossAt: 42,
    waves: [
      { t: 2.0, f: (S) => { S.spawn('ghost', 0.4); S.spawn('ghost', 0.6); } },
      { t: 5.0, f: (S) => S.spawn('lanternTop', 0) },
      { t: 7.5, f: (S) => S.spawn('lantern', 0.6) },
      { t: 10.5, f: (S) => S.spawnV('fish', 0.5, 5) },
      { t: 13.5, f: (S) => S.spawnRow('gullDive', [0.35, 0.65]) },
      { t: 17.0, f: (S) => { S.spawn('ghost', 0.25); S.spawn('ghost', 0.75); } },
      { t: 20.0, f: (S) => { S.spawn('lanternTop', 0); S.spawn('lantern', 0.7) ; } },
      { t: 23.5, f: (S) => S.drop('power', 0.5) },
      { t: 25.5, f: (S) => S.spawnRow('mine', [0.3, 0.6]) },
      { t: 28.5, f: (S) => S.spawn('octoBack', 0.5) },
      { t: 32.0, f: (S) => { S.spawn('ghost', 0.3); S.spawn('ghost', 0.5); S.spawn('ghost', 0.7); } },
      { t: 35.5, f: (S) => S.spawnV('fish', 0.4, 5) },
      { t: 38.5, f: (S) => S.drop('bomb', 0.5) },
    ],
  },
  {
    name: '3-2 ちょうちん まつり', sub: 'ひのともる そら', bg: 'sh_bg_night', night: true,
    music: 'night', boss: 'mid_lantern', bossHpMul: 1.3, factId: 'ito_onsen', clearSprite: 'ryokan',
    bossAt: 45,
    waves: [
      { t: 2.0, f: (S) => { S.spawn('lanternTop', 0); S.spawn('lanternTop', 0); } },
      { t: 5.5, f: (S) => { S.spawn('lantern', 0.3); S.spawn('lantern', 0.7); } },
      { t: 9.0, f: (S) => S.spawnRow('gullDive', [0.3, 0.5, 0.7]) },
      { t: 12.5, f: (S) => { S.spawn('ghost', 0.2); S.spawn('ghost', 0.5); S.spawn('ghost', 0.8); } },
      { t: 16.0, f: (S) => S.spawnRow('mine', [0.25, 0.5, 0.75]) },
      { t: 19.5, f: (S) => { S.spawn('octoBack', 0.35); S.spawn('octo', 0.7); } },
      { t: 23.0, f: (S) => S.drop('power', 0.45) },
      { t: 25.0, f: (S) => { S.spawn('lanternTop', 0); S.spawnV('fish', 0.6, 5); } },
      { t: 28.5, f: (S) => { S.spawn('ghost', 0.35); S.spawn('ghost', 0.65); S.spawn('tobiuoLeap', 0); } },
      { t: 32.0, f: (S) => S.spawnRow('gullDive', [0.25, 0.55]) },
      { t: 35.0, f: (S) => S.spawnRow('mine', [0.2, 0.45, 0.7]) },
      { t: 38.5, f: (S) => S.drop('heart', 0.5) },
      { t: 40.5, f: (S) => { S.spawn('lantern', 0.25); S.spawn('lantern', 0.75); } },
    ],
  },
  {
    name: '3-3 おんせんがいの けっせん', sub: 'ウニ大魔王 あらわる', bg: 'sh_bg_night', night: true,
    music: 'night', boss: 'urchin', bossHpMul: 1, factId: 'ito_onsen', clearSprite: 'ryokan',
    worldEnd: true, final: true, bossAt: 52,
    waves: [
      { t: 2.0, f: (S) => { S.spawn('ghost', 0.35); S.spawn('ghost', 0.65); } },
      { t: 5.0, f: (S) => { S.spawn('lanternTop', 0); S.spawn('lantern', 0.6); } },
      { t: 8.5, f: (S) => S.spawnRow('mine', [0.2, 0.4, 0.6, 0.8]) },
      { t: 12.0, f: (S) => S.spawnRow('gullDive', [0.3, 0.5, 0.7]) },
      { t: 15.5, f: (S) => { S.spawn('octoBack', 0.3); S.spawn('octoBack', 0.7); } },
      { t: 19.5, f: (S) => S.spawnV('fish', 0.5, 7) },
      { t: 23.0, f: (S) => { S.spawn('ghost', 0.25); S.spawn('ghost', 0.5); S.spawn('ghost', 0.75); } },
      { t: 26.5, f: (S) => S.drop('power', 0.4) },
      { t: 28.5, f: (S) => { S.spawn('lanternTop', 0); S.spawn('lanternTop', 0); } },
      { t: 32.0, f: (S) => { S.spawnRow('mine', [0.3, 0.7]); S.spawn('octo', 0.5); } },
      { t: 35.5, f: (S) => S.spawnRow('gullDive', [0.2, 0.45, 0.7]) },
      { t: 39.0, f: (S) => { S.spawn('tobiuoLeap', 0); S.spawn('tobiuoLeap', 0); S.spawn('tobiuoLeap', 0); } },
      { t: 42.5, f: (S) => { S.spawn('ghost', 0.4); S.spawn('ghost', 0.6); } },
      { t: 45.5, f: (S) => S.drop('bomb', 0.5) },
      { t: 47.5, f: (S) => { S.spawn('lantern', 0.3); S.spawn('lantern', 0.7); } },
      { t: 49.5, f: (S) => S.spawnV('fish', 0.5, 6) },
    ],
  },
];

window.SSTAGES = SSTAGES;
